import CoreConcepts from "./components/CoreConcept/CoreConcept";
import Header from "./components/Header/Header";
import { CORE_CONCEPTS } from "./data";

// The idea behind JSX is that you have an easier time defining the
// target HTML code that should be generated by your components.

// Your JSX code leads to a tree-like code structure that "tells" React how the different
// components are related and how the UI should look like. It then executes appropriate
// commands to manipulate the real DOM to reflect that target structure / code.

function App() {
  return (
    <div>
      <Header />
      <main>
        <section id="core-concepts">
          <h2>Core Concepts</h2>
          <ul>
            <CoreConcepts
              title={CORE_CONCEPTS[0].title}
              description={CORE_CONCEPTS[0].description}
              image={CORE_CONCEPTS[0].image}
            />
            {/*shortcut! */}
            <CoreConcepts {...CORE_CONCEPTS[1]} />
            <CoreConcepts {...CORE_CONCEPTS[2]} />
            <CoreConcepts {...CORE_CONCEPTS[3]} />
          </ul>
        </section>
      </main>
    </div>
  );
}

export default App;
