import CoreConcepts from "./components/CoreConcept/CoreConcepts";
import Examples from "./components/Examples";
import Header from "./components/Header/Header";

// The idea behind JSX is that you have an easier time defining the
// target HTML code that should be generated by your components.

// Your JSX code leads to a tree-like code structure that "tells" React how the different
// components are related and how the UI should look like. It then executes appropriate
// commands to manipulate the real DOM to reflect that target structure / code.

function App() {
  return (
    <>
      <Header />
      <main>
        <CoreConcepts />
        <Examples />
      </main>
    </>
  );
}

export default App;
